type Link {
    opponents: String
    opponentsreps: String
    challengetype: String
    challengereps: String
    challengerules: String
    opponentspushSubscriptions: String
}

# type Query {
#     link(identifier: String!): [Link!]!
# }

type Query {
    allLinks: [Link!]!
}
